FROM python:3.10

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y build-essential default-libmysqlclient-dev make && rm -rf /var/lib/apt/lists/*

# Install test Python requirements
COPY requirements/ ./requirements/
RUN pip install --no-cache-dir -r requirements/test.txt

# Copy the test runner script
COPY docker/run-tests.sh /run-tests.sh
RUN chmod +x /run-tests.sh

# Run the test runner
CMD ["/run-tests.sh"]
