# 01-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog
spec:
  selector:
    matchLabels:
      app: microblog
  replicas: 2
  template:
    metadata:
      labels:
        app: microblog
    spec:
      containers:
      - image: stonie24/microblog:v14.0.5
        imagePullPolicy: Always
        name: microblog
        env:
          - name: FLASK_APP
            value: microblog

          - name: FLASK_ENV
            value: production

          - name: DATABASE_URL
            value: mysql+pymysql://microblog:microblogpass@mysql/microblog
        ports:
        - containerPort: 5000